### ISSUE TITLE
How to make this work with velodyne32

### ISSUE THREAD

**Issue by Zhousiyuhit** [ANYbotics/elevation_mapping#104]
Dear Author, I am sorry to bother you again, I have tried to use Velodyne32 to your project, I tried "roslaunch velodyne_description example.launch" as a gazebo simulator. And I advertise the Pose with tf, however I get the result like this:
![velodyne](https://user-images.githubusercontent.com/24530382/56567570-cba5c400-65e7-11e9-9635-b749916f97d4.png)
The result show that the map is separately, 
and my parameters is imitative of the struct_light parameters:
 
![parameters](https://user-images.githubusercontent.com/24530382/56567822-4ec71a00-65e8-11e9-8c0d-f063e1fcee10.png)
I am so confused with it, could you please tell me how to work with Velodyne32? Thanks sincerely!!

**Comment by YoshuaNava** [comment]
Hi @Zhousiyuhit,
I think the main problem is that the tf trees of your robot, and the velodyne hdl32 are not connected correctly. I would suggest inspecting the transformations between all your sensors (in rviz, or using [tf tools](http://wiki.ros.org/tf/Debugging%20tools)).

Maybe you could use this as a reference on how to add a Velodyne sensor (in this case VLP-16) to your robot URDF? https://github.com/njkaiser/nu_jackal_autonav/blob/master/urdf/jackal.urdf.xacro#L233

**Comment by maximilianwulf** [comment]
Hi @Zhousiyuhit,
As @YoshuaNava suggested, you have to check the tf tree. Once you figured out the frame id's you can add them to [this file](https://github.com/ANYbotics/elevation_mapping/blob/master/elevation_mapping_demos/config/robots/simple_demo_robot.yaml) or any other in that folder. Make sure to update the _map_frame_id_, _robot_base_frame_id_ and _track_point_frame_id_.

**Comment by maximilianwulf** [comment]
Furthermore, for the parameters, you can use [velodyne_HDL-32E.yaml](https://github.com/ANYbotics/elevation_mapping/blob/master/elevation_mapping/config/sensor_processors/velodyne_HDL-32E.yaml).

**Comment by LZMHIT** [comment]
@maximilianwulf I am the partner of @Zhousiyuhit, Thank you for your answer, we have made a check, we think the tf tree is complete, and the frame_ids are all updated corresponding to the tf frame.  Frame velodyne2 is the sensor frame and velodyne2_base_link is its base frame.
![tf](https://user-images.githubusercontent.com/23434354/56581877-880f8200-6608-11e9-85ba-682921f1a47c.png)
![set_frame](https://user-images.githubusercontent.com/23434354/56581879-8a71dc00-6608-11e9-9ff7-40bf5fe88de0.png)
Is there any wrong with our settings?Besides, your project is running successfully with out any fault. However there is no terrain in rviz. Do you have any example of velodyne32 shared? Thank you very much.

**Comment by YoshuaNava** [comment]
Hi @LZMHIT 
From the above image I can see that you don't have any [world-fixed frame](https://www.ros.org/reps/rep-0105.html) in your tf tree. This is needed by elevation_mapping.

**Comment by LZMHIT** [comment]
Hi @YoshuaNava 
I have the world-fixed frame, it is base_footprint,and in my setting the map_frame_id is just base_footprint
![2019-04-23 21:05:24屏幕截图](https://user-images.githubusercontent.com/23434354/56583176-927f4b00-660b-11e9-8d52-c4067a987a11.png)

**Comment by YoshuaNava** [comment]
Do you see any warnings from elevation_mapping in the console?

**Comment by LZMHIT** [comment]
Hi @YoshuaNava 
Only the first time it started there is an warning, after that I didn't see any warnings or wrong 
![run](https://user-images.githubusercontent.com/23434354/56583937-4df4af00-660d-11e9-8600-5dcef3f2b4c7.png)

**Comment by maximilianwulf** [comment]
Your settings look correct so far. 

Can you check if the elevation mapping node is publishing an elevation mapping topic with `rostopic hz /topic_name`.

Furthermore, to see the elevation map in RVIZ you have to add the grid map plugin. You should be able to access it with the 'Add' button.

![rivz](https://user-images.githubusercontent.com/5656831/56584041-2f75c000-65db-11e9-9847-b8b7bf99326c.png)

**Comment by maximilianwulf** [comment]
Your console output looks fine. Elevation map is subscribing to the point cloud topic and is updating the map. You should be able to see it in RVIZ.

**Comment by LZMHIT** [comment]
Hi @maximilianwulf 
Thank you for your advice, I have added it, in the following picture, I can see the beautiful map when I zoom in it, however it is a little and is not continuously, and the topic is not always nan
![map](https://user-images.githubusercontent.com/23434354/56584582-9bbde700-660e-11e9-8dcc-518192e9b855.png)
![topic](https://user-images.githubusercontent.com/23434354/56584585-9cef1400-660e-11e9-9ab6-d5405fac9dbb.png)

**Comment by maximilianwulf** [comment]
Hi @LZMHIT, by looking at your console output it everything seems okay.
There is a new pull request #105  with an example that uses the turtlebot3 simulation. The settings are correct and it could you help integrate it into your solution.

**Comment by brunoeducsantos** [comment]
Hi @maximilianwulf ,
I am trying to use ouster lidar 64 in elevation_mapping. My tf tree is:

![image](https://user-images.githubusercontent.com/3111976/63843836-f67d9b80-c97e-11e9-88d3-cbe53001694b.png)

And my configuration file is:

```
point_cloud_topic: "/os1_cloud_node/points"
map_frame_id: "odom"
robot_base_frame_id: "base_link"
sensor_frame_id: "os1_lidar"
robot_pose_with_covariance_topic: "/base_link_pose"
robot_pose_cache_size: 200
track_point_frame_id: "base_link"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
 
```

The following issue is coming up when running elevation_mapping node:

```
[ERROR] [1566985013.395180598, 1551442133.538437939]: Lookup would require extrapolation into the past.  Requested time 614.657018000 but the earliest data is at tim
e 1551442129.432109387, when looking up transform from frame [os1_lidar] to frame [odom]
[ERROR] [1566985013.395503711, 1551442133.538437939]: Point cloud could not be processed.
```

Any thoughts what could be happening?
Thanks,
Bruno

**Comment by YoshuaNava** [comment]
Hi @brunoeducsantos,
It seems that your Lidar data is coming in with a really old timestamp: 614.657018000 seconds.  In Unix time, that is:
![Screenshot_2019-08-28_13-27-10](https://user-images.githubusercontent.com/7463211/63851994-93e4c980-c997-11e9-93d8-a531490d1ea8.png)
Source: https://www.unixtimestamp.com/index.php

From what I know, the Ouster driver uses ros::Time to stamp sensor data. And you seem to be running the Lidar on a PC with a date not properly set. I would recommend that you check the clock of all the PCs that will be interacting in your robot.

Please let me know if this helps.

Best,
Yoshua Nava

**Comment by brunoeducsantos** [comment]
Thanks @YoshuaNava . I will check out if that solves my issue.

**Comment by maximilianwulf** [comment]
Hi @brunoeducsantos, does it work now with your setup?

**Comment by brunoeducsantos** [comment]
Hi @maximilianwulf, 
Sorry for the late response. I sorted out the issue by overriding the time stamp and republish it.
Thanks for the query.

**Comment by maximilianwulf** [comment]
@brunoeducsantos, good to hear. 
I will close this issue, feel free to reopen if further assistance is needed.
