### ISSUE TITLE
Dropping connection for different md5sum

### ISSUE THREAD

**Issue by h-ss** [ANYbotics/elevation_mapping#121]
Hi,
I have the following issue when launch elevation_mapping_demos:
[ERROR] [1574347313.217889973]: Client [/elevation_mapping] wants topic /orb_slam2_rgbd/pose to have datatype/md5sum [geometry_msgs/PoseWithCovarianceStamped/953b798c0f514ff060a53a3498ce6246], but our version has [geometry_msgs/PoseStamped/d3812c3cbc69362b77dc0b19b345f8f5]. Dropping connection.

I'm using ros kinetic on ubuntu 16, can it be solved?

**Comment by maximilianwulf** [comment]
Hey @h-ss, sure the pose is missing the covariance. Elevation mapping relies on a covariance. In case you don't want to provide it you can overwrite it with 0.
