### ISSUE TITLE
 Could not get pose information from robot 

### ISSUE THREAD

**Issue by Old-Man-Reality** [ANYbotics/elevation_mapping#123]
I want to add my realsense  camera point_cloud topic to build  a elevation_mapping ,but I can't get the pose information.How can I add my realsense camera's pose information to a demo?
[ERROR] [1574665072.180786107, 1.140000000]: Could not get pose information from robot for time 1574665072.055160. Buffer empty?
[ERROR] [1574665072.180813792, 1.140000000]: Updating process noise failed.

**Comment by maximilianwulf** [comment]
Hey @Old-Man-Reality, I think this is the same problem as in #122.

**Comment by maximilianwulf** [comment]
Feel free to reopen if you think it is not a duplicate.
