### ISSUE TITLE
unit tests error

### ISSUE THREAD

**Issue by infinity0323** [ANYbotics/elevation_mapping#126]
Hi.
**When I run the unit tests with**

catkin_make run_tests_elevation_map_msg run_tests_elevation_mapping

 **it shows the following error :**
 make:***no rules to make target “run_tests_elevation_map_msg”.Stop.

**Can u tell me why? Thanks a lot.
I have already built 'catkin_ws' correctly.**

**Comment by maximilianwulf** [comment]
Hi @infinity0323, in order to use the package, you don't need to run the unit tests. 
What is your plan with elevation mapping?

**Comment by infinity0323** [comment]
> Hi @infinity0323, in order to use the package, you don't need to run the unit tests.
> What is your plan with elevation mapping?

I want to use it to do the path planning of UAV.
I don't know if it is appropriate.
Still learning. 
Do you have any suggestions？>_<

**Comment by maximilianwulf** [comment]
Yes, check these papers: 

[Active autonomous aerial exploration for ground robot path planning](https://www.zora.uzh.ch/id/eprint/138916/1/RAL16_Delmerico.pdf)

[Collaborative localization of aerial and ground robots through elevation maps](https://www.zora.uzh.ch/id/eprint/127901/1/SSRR16_Kaeslin.pdf)
