### ISSUE TITLE
about continuous cleanup

### ISSUE THREAD

**Issue by pxlong** [ANYbotics/elevation_mapping#132]
Hi, thx for sharing this great mapping tool.

I am using a Livox Lidar (mid-100) to publish point clouds in 2Hz. 
I have found that if I set enable_continuous_cleaup to true, it will not publish elevation map, and I can not see the GridMap in rviz. Is there something wrong / misunderstanding? 

I want the elevation map is always created from the latest point cloud. How to set the configuration to meet this requirement?

**Comment by pxlong** [comment]
I have found that if I set enable_continuous_cleaup to true, it will be stuck at the **`map_.clear();`**

**Comment by maximilianwulf** [comment]
Hi @pxlong, 

> I want the elevation map is always created from the latest point cloud. How to set the configuration to meet this requirement?

`enable_continuous_cleaup` is the correct option for this. `map.clear()` can be slow, but it should never get stuck. If you don't need fusing of the elevation map you can turn it off. In this case the `map.clear()` function should be faster.
