### ISSUE TITLE
How can I get the costmap of elevation_map from the topic?

### ISSUE THREAD

**Issue by SUN-GE** [ANYbotics/elevation_mapping#145]
Thanks for your excellent work! 

I have run the demo successfully. I'd like to ask is there any directly way that I could get the costmap from the elevation map's topic? 

Looking forward to your reply. Thanks a lot.

**Comment by usamex** [comment]
I had been looking for this as well and I guess there's no option but to implement your own costmap plugin. You can find an excellent example in the PR (Pull Request Section) #84 . Hope this helps.

**Comment by maximilianwulf** [comment]
Hi @SUN-GE, @usamex is right, at the moment the package does not support costmaps. The grid_map package provides functionalities to convert height maps to costmaps, see [here](https://github.com/ANYbotics/grid_map/tree/master/grid_map_costmap_2d). 

For the moment, you will have to implement this feature by yourself. We do not plan to integrate it.

**Comment by SUN-GE** [comment]
Thanks for your advice! @usamex @maximilianwulf

**Comment by hzyhuter** [comment]
@usamex hey Thank you for giving me this advice, can you teach me the exact use of this plugin? I am new in this area. Appreciate it!
