### ISSUE TITLE
Throwing std::bad_alloc for aparently no reason

### ISSUE THREAD

**Issue by caiofis** [ANYbotics/elevation_mapping#147]
I am using the package on some bags recorded on my robot equipped with a velodyne puck and it is working like a charm.  
But sometimes it just breaks throwing a std::bad_alloc and I am not able to trace where it is coming from.
Using Valgrind the error didn't occurred and using gdb I got the following error:

![image](https://user-images.githubusercontent.com/17056511/101905711-a0922e80-3b96-11eb-90dd-7440aaaa45e3.png)

Does anyone faced this issue before?

**Comment by maximilianwulf** [comment]
Hi @caiofis, can you `bt` in the gdb to see at what line the the software crashed?

**Comment by caiofis** [comment]
Sure!
It seems to be happening in the publishFusedMapCallback, but it is weird that the program run for a while before crashing.
![image](https://user-images.githubusercontent.com/17056511/101913813-426b4880-3ba2-11eb-95db-010ed124b339.png)

**Comment by maximilianwulf** [comment]
Can you `list` in frame 8?

**Comment by caiofis** [comment]
Here it goes
![image](https://user-images.githubusercontent.com/17056511/101927322-1a381580-3bb3-11eb-92e5-f40c5f4c0cf7.png)

**Comment by caiofis** [comment]
I was able to stop the std::bad_alloc using the hack proposed in #42, but using a hard-coded maximum.
My point cloud is quite sparse, I am wondering if the lack of observations on some cells for some time would make the error ellipse grow, resulting on a massive number of points fused, leading to the bad allocation.

My hack bellow line 312 of [ElevationMap.cpp](https://github.com/ANYbotics/elevation_mapping/blob/master/elevation_mapping/src/ElevationMap.cpp#L311):
```cpp
if (maxNumberOfCellsToFuse > 1000) {
    // Skip fusing.
      fusedMap_.at("elevation", *areaIterator) = rawMapCopy.at("elevation", *areaIterator);
      fusedMap_.at("lower_bound", *areaIterator) = rawMapCopy.at("elevation", *areaIterator) - 2.0 * sqrt(rawMapCopy.at("variance", *areaIterator));
      fusedMap_.at("upper_bound", *areaIterator) = rawMapCopy.at("elevation", *areaIterator) + 2.0 * sqrt(rawMapCopy.at("variance", *areaIterator));
      fusedMap_.at("color", *areaIterator) = rawMapCopy.at("color", *areaIterator);
      continue;
    }
```
Image from the sparse point cloud on Rviz:
![image](https://user-images.githubusercontent.com/17056511/101938383-ffb96880-3bc1-11eb-9532-107c7ef1f702.png)

**Comment by maximilianwulf** [comment]
Thank you for this observation. We will follow up on this. 

But for now you are not blocked?

**Comment by caiofis** [comment]
I am not blocked anymore, thank you so much for your help. Please send me a notice when you figure out a more elegant solution to this issue. :)

**Comment by maximilianwulf** [comment]
We will do :)
