### ISSUE TITLE
Long running program crashes 

### ISSUE THREAD

**Issue by liuzm-slam** [ANYbotics/elevation_mapping#154]
l run this program for short time, but have a problem, l hope get your help.

![Screenshot from 2021-01-25 09-47-20](https://user-images.githubusercontent.com/72718752/105652312-e3fcee00-5ef3-11eb-9208-8c8996a3bf3b.png)
![Screenshot from 2021-01-25 09-48-26](https://user-images.githubusercontent.com/72718752/105652315-e5c6b180-5ef3-11eb-80a4-55160fb5a1a2.png)

**Comment by liuzm-slam** [comment]
l have slove this problem, l download a old package about grid_map (the newest rviz plugin in kinetic have problem)

**Comment by maximilianwulf** [comment]
Hi @liuzm-slam, yes Kinetic users should use an older version. Sorry for the inconviences.
