### ISSUE TITLE
hello,I want  to use livox lidar to generate elevation map, this package is ok?
Thanks!

### ISSUE THREAD

**Issue by wzy012** [ANYbotics/elevation_mapping#166]

**Comment by maximilianwulf** [comment]
Yes, this package is suitable for different sensors.

**Comment by wzy012** [comment]
> Yes, this package is suitable for different sensors. 

Thank you very much!
If I want to run the package(elevation mapping) successfully，I need to provide sensors point cloud and pose from imu or others?

**Comment by wzy012** [comment]
@maximilianwulf I run this package with livox successfully！

**Comment by maximilianwulf** [comment]
Nice, glad to hear that.
