### ISSUE TITLE
elevation map sometimes normal and sometimes abnormal

### ISSUE THREAD

**Issue by wzy012** [ANYbotics/elevation_mapping#169]
Hi，
Thanks for your contribution!
I have some problems running this package:
Firstly,I use the odometry (nav_msgs/Odometry) type data to generate pose ,and point cloud to elevation map.
But it is have problems:
on terminal ,it is showing:Couldn't get pose information from robot for time…Buffer empty?
(rviz don't have elevation map)
But after a while，rviz has elevation map and terminal is not showing can'tget pose information….
After a while，elevation map is not update and terminal shows can't get pose information.
Can you get me some help or suggest ion.I don't know this reason.
Thanks!

**Comment by maximilianwulf** [comment]
Hey @wzy012, could it be that you have to update the config file with the topic name?

**Comment by wzy012** [comment]
> Hey @wzy012, could it be that you have to update the config file with the topic name? 

yes，I update the config file.

**Comment by maximilianwulf** [comment]
Can you double-check the topic message type?

**Comment by wzy012** [comment]
> Can you double-check the topic message type? 

year，I know！ Then I will reply to you after check.

**Comment by maximilianwulf** [comment]
Hey, could you comment what helped you in the end?

**Comment by wzy012** [comment]
The main cause of this problem is that pointcloud source.The package I used was changed by some company and it's time precise is low,low matching degree with the ros timestamp.The problem was solved after I switched to the official package.

**Comment by maximilianwulf** [comment]
Great to hear :+1:
