### ISSUE TITLE
Ubuntu16.04 kinetic using elevation map package 

### ISSUE THREAD

**Issue by wzy012** [ANYbotics/elevation_mapping#171]
Hi，I run elevation mapping package successfully on Ubuntu18.04，but l run it on Ubuntu.16.04,I find the version is not match.
grid map version is 1.6,
elevation mapping is latest master branch，but in terminal showing error.when I use elevation mapping is 0.5/0.6 ,it's not errors,catkin successfully,but it has not turtlebot simulator.
what version  should I use in Ubuntu16.04，and it could use turtlebot to simulate.
Thanks!

**Comment by wzy012** [comment]
errors are:
…/elevation_mapping/src/input_sources
/Input.cpp:42:32:error:passing 'const XmlRpc::XmlRpcValue' as 'this' argument discards qualifiers [-fpermkssive]

**Comment by wzy012** [comment]
I have solved this problem,I update "xmlrpcpp" by apt,then catkin build!
my versions are:
ros:kinetic
pcl:1.11
eigen:3.3.4
grid_map:1.6.2
elevation_mapping:master
For others reference!
you can close this answer!
Thanks!

**Comment by maximilianwulf** [comment]
Thank you.
