### ISSUE TITLE
the processing way of muliple sensors

### ISSUE THREAD

**Issue by YinghaoJia98** [ANYbotics/elevation_mapping#187]
There are some noises when using multiple snesors providing pointcloud.

**Comment by maximilianwulf** [comment]
Can you share some screenshots? 

Also you can use post processors to get rid of noise.

**Comment by YinghaoJia98** [comment]
@maximilianwulf Thanks a lot for your reply, this problom has been solved by preprocessing point cloud from lidar.

**Comment by maximilianwulf** [comment]
Great, would you mind adding some examples here for future travelers?

**Comment by YinghaoJia98** [comment]
@maximilianwulf It's such a compromise that giving up using point cloud close to robot from lidar and establishing elevation map near the robot by using realsense d435i.
