### ISSUE TITLE
Why are there so many holes and how to solve them?

### ISSUE THREAD

**Issue by DLonng** [ANYbotics/elevation_mapping#193]
![2021-11-29_19-45](https://user-images.githubusercontent.com/12621722/143862650-584b00f7-af40-4801-ba3f-b1fdc8863047.png)

**Comment by maximilianwulf** [comment]
Hey @DLonng, it seems your point clouds are not dense enough, 2 possible options: 

- When the robot moves the holes get filled once a point from a point cloud falls into it. 
- You add a postprocessor pipeline to the elevation mapping which fills small holes, we currently recommend this one: https://github.com/ANYbotics/grid_map/blob/master/grid_map_filters/include/grid_map_filters/MedianFillFilter.hpp

**Comment by DLonng** [comment]
> 
![2021-11-30_15-49](https://user-images.githubusercontent.com/12621722/144006897-137b04b7-9f27-495f-ac71-9dc7182bfe6f.png)
very good!!! hahhaaa :)

**Comment by maximilianwulf** [comment]
Nice, seems to work. Will close the issue, feel free to re-open if you need further assistance.

**Comment by hzyhuter** [comment]
hey，can you teach me how to use the MedianFillFilter? thank you very much!
