### ISSUE TITLE
Leveraging grid map history displayed in Rviz

### ISSUE THREAD

**Issue by sarahnator** [ANYbotics/elevation_mapping#200]
I noticed that Rviz displays a cache of grid maps, does elevation_mapping make it possible to access this historical grid map through the code interface? It seems that the topics publish just the instantaneous elevation map and the services make it possible to only access a submap portion unless I am mistaken.

**Comment by Magnusgaertner** [comment]
Hi @sarahnator, 

The cache happens on the client side (the rviz plugin for grid_map). Here, the cache allows displaying the n most recent messages for a given grid_map topic. 

elevation_mapping does not store an explicit history of grid_maps, but uses an online filtering approach (Kalman filter) to update an estimate of the current state. 

If you wish to have such functionality, I suggest to either

- Subscribe and cache the messages yourself on the client-side
-  Modify your fork of elevation_mapping to add a buffer that is filled whenever the internal state is updated. 

Best, 
Magnus
