### ISSUE TITLE
Generated elevation_map is floating in the air

### ISSUE THREAD

**Issue by Yaru-Gu** [ANYbotics/elevation_mapping#202]
Hello,

Thank you for sharing this remarkable work!
I'm trying to use this package with a quadruped robot. I tested using the environment _turtlebot3_house.world_ for my robot to walk through. Everything else works fine, but the generated elevation_map is not standing on the ground. Please see the attached image for better illustration. The mapped floor of the _turtlebot3_house.world_ is floating in the air, and my robot is buried by it. 
![Screenshot from 2022-02-15 16-01-28](https://user-images.githubusercontent.com/96481145/154135724-f4123e63-c624-4216-9e59-f773e7613b3a.png)
 
I have no clue where to adjust it. Any help would be very much appreciated.

**Comment by zhanghua7099** [comment]
Hi! It may be caused by the initial coordinate system of the SLAM algorithm. I guess the initial pose is not aligned to gravity. 

You can try to adjust the orientation of the camera (parallel to the ground). Or try to align the initial coordinate system with the direction of gravity.

**Comment by Yaru-Gu** [comment]
This problem has been solved by using more precise inertial values for all links.
