### ISSUE TITLE
How to get the value of terrain elevation?

### ISSUE THREAD

**Issue by Yaru-Gu** [ANYbotics/elevation_mapping#204]
Hi,

I'm wondering how I can get the value of terrain elevation (z) on a position specified by (x,y) in the robot base frame.

Any help would be appreciated.

**Comment by shivauchiha** [comment]
multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]
i = row
j = column
k = channel

**Comment by Yaru-Gu** [comment]
I solve the problem by using function `map_.fusedMap_.at("elevation", index)` in _ElevationMapping.cpp_
