### ISSUE TITLE
Missing versions of dependencies 

### ISSUE THREAD

**Issue by valli96** [ANYbotics/elevation_mapping#213]
Is there a **list of versions of dependencies** with which the project starts, in any case.  
I have changed many dependencies without success. From the error messages, I can not conclude what should change.
See #212. Thanks in advance

**Comment by maximilianwulf** [comment]
You can check launch file dependencies with `roslaunch-deps -v file.launch`

and package dependencies with `rospack depends elevation_mapping`. 

Does that answer your question.

**Comment by valli96** [comment]
Thank you the tip. The missing package in my case was `pcl_msg`
