### ISSUE TITLE
The flat ground maps are cluttered with color

### ISSUE THREAD

**Issue by lancelonginus** [ANYbotics/elevation_mapping#251]
The flat ground maps are cluttered with color！Shouldn't there normally be only one color and how to adjust it.
![2567afb93346165dde522edd9abc77d](https://github.com/ANYbotics/elevation_mapping/assets/128156238/8585f5be-fa74-4430-ba46-a2c99db88993)

**Comment by Muhammad540** [comment]
> The flat ground maps are cluttered with color！Shouldn't there normally be only one color and how to adjust it. ![2567afb93346165dde522edd9abc77d](https://private-user-images.githubusercontent.com/128156238/296265648-8585f5be-fa74-4430-ba46-a2c99db88993.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzOTc2NDAsIm5iZiI6MTcyMTM5NzM0MCwicGF0aCI6Ii8xMjgxNTYyMzgvMjk2MjY1NjQ4LTg1ODVmNWJlLWZhNzQtNDQzMC1iYTQ2LWEyYzk5ZGI4ODk5My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQxMzU1NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzFlMzZjMjVmYTIzYzJiNThlZmU2ZGNmMTZmMDE3MDlhODBmODBlMWY3NzNjZTM5ZmY4NGNiOGU5YTNlMzMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tVyVrat6A7u9dV0qAg4SiQ7iTV8UEddS73044_eY618)

Hey @lancelonginus , were you able to figure out this issue, since i am also experiencing this ?
