### ISSUE TITLE
Is it can use hokuyo 2d pointcloud build elevation map?

### ISSUE THREAD

**Issue by JianXingChen** [ANYbotics/elevation_mapping#43]
I use hokuyo utm30lx laserscan transform to pointcloud2,and use rovio odometry as 6d pose.but the console display " can not get msg from sensor".And i have been success in kinect pointcloud.
I want to know whether is  it can use hokuyo 2d pointcloud2 to  build EM.

**Comment by maximilianwulf** [comment]
Hi @JianXingChen, 
it should work with the corresponding [yaml file](https://github.com/ANYbotics/elevation_mapping/blob/master/elevation_mapping/config/sensor_processors/hokuyo_utm-30lx.yaml) for the hokuyo sensor. You can replace it accordingly in your launch file.

Feel free to reopen the issue if your question is not answered.
