### ISSUE TITLE
Updating map in real-time

### ISSUE THREAD

**Issue by johndevera** [ANYbotics/elevation_mapping#53]
I'm having trouble getting the map to update as soon as it has scanned an area. I've modified the various updating and publishing parameters to 1 hz but when viewed in Rviz it appears to update at random times, almost 10-20 seconds after scanning an area. In your video with the 4 legged robot over the rubble scene, the map appears to be saving and updating in realtime. What can you suggest is a good way to do that?

**Comment by wojiaojiao** [comment]
@johndevera do you solve it?i have issues same with you

**Comment by wojiaojiao** [comment]
@johndevera do you solve it?i have issues same with you

**Comment by Rayman** [comment]
Did you compile in release mode? This solved most of the issues for me
```
catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release
```

**Comment by maximilianwulf** [comment]
Closing because of missing follow up. Feel free to reopen.
