### ISSUE TITLE
Converting from grid_map_msgs:GridMap

### ISSUE THREAD

**Issue by johndevera** [ANYbotics/elevation_mapping#54]
The elevation_map type is of grid_map_msgs::GridMap. Is there a way to convert this to grid_map::GridMap? Can you recommend a good way to work with this data for visualizing as a 2d map?

**Comment by maximilianwulf** [comment]
Hi @johndevera.

> The elevation_map type is of grid_map_msgs::GridMap. Is there a way to convert this to grid_map::GridMap?

Yes, the function [fromMessage](https://github.com/ANYbotics/grid_map/blob/c4a16b71d40c2c6df8d60b1c91cd78616f9db672/grid_map_ros/src/GridMapRosConverter.cpp#L38) in the grid_map_ros package can do that.

> Can you recommend a good way to work with this data for visualizing as a 2d map?

The [grid_map_rviz_plugin](https://github.com/ANYbotics/grid_map/tree/master/grid_map_rviz_plugin) should do the visualization.
